config/routes.rb
Hermes::Application.routes.draw do
  
  match "/clear_resolved" => 'messages#clear_resolved'

  # message sources
    get "message_source/directory", as: 'message_source_directory'
    get "message_source/mine", as: 'my_message_sources'
    # post "message_sources/:message_id/check"

  resources :presentations
  match "/presentations_index_for_rule" => "presentations#index_for_rule"

  resources :rules
  match "/rules_index_for_inbox" => "rules#index_for_inbox"

  resources :traits


  resources :messages
  match '/resolve_message' => 'messages#resolve'

  resources :rss_feeds


  resources :inboxes
  match '/inbox_resolve_all_messages' => 'inboxes#resolve_all_messages'
  match '/inbox_check_for_messages' => 'inboxes#check_for_messages'
  match '/pull' => 'inboxes#pull'

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout
    
  resources :users

  root :to => 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :resolved, :message_source_id, :message_source_type, :read, :traits_hash, :unique_identifier

  belongs_to :message_source, polymorphic: true
  has_many :traits, as: :traited, dependent: :destroy
  has_many :presentations, dependent: :destroy
  has_many :inboxes, through: :presentations

  def source
    if self.message_source_type == "RssFeed"
      self.message_source.name+" (RSS)"
    elsif self.message_source_type == "Authorization"
      user_traits = self.traits.where(name:"user_screen_name")
      if user_traits.first
        "@"+ user_traits.first.value
      else
        "Unknown User"
      end
    end
  end

  def distribute!
    if self.message_source && self.message_source.user
      self.message_source.user.rules.each do |rule|
        rule.process(self)
      end
    end
  end

  def value(name)
  	case name
		when 'message_source_id'
			self.message_source_id
		when 'message_source_type'
			self.message_source_type
		when 'hermes_received_time'
			self.created_at.to_s
		when 'read'
			self.read
		when 'resolved'
			self.resolved
    else
      if trait = self.traits.where(name:name).first
        return self.traits.where(name:name).first.value
      else
        return nil
      end
    end
  end

  def message_subject
    if trait = Trait.where(traited_type:'Message',traited_id:self.id,name:'title').first
     trait.value
    else
      "unknown subject"
    end
  end

  def pull_json(traits = [])
    message = {}

    message["source"] = self.source
    message["title"] = self.message_subject
    message["id"] = self.id
    message["url"] = self.value("url")

    traits.each do |t|
      message[t] = self.value(t)
    end

    return message
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  # scaffold methods
    def index
      @messages = Message.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @messages }
      end
    end

    # GET /messages/1
    # GET /messages/1.json
    def show
      @message = Message.find(params[:id])

      # mark message as read
        @message.read = true
        @message.save

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @message }
      end
    end

    # GET /messages/new
    # GET /messages/new.json
    def new
      @message = Message.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @message }
      end
    end

    # GET /messages/1/edit
    def edit
      @message = Message.find(params[:id])
    end

    # POST /messages
    # POST /messages.json
    def create
      @message = Message.new(params[:message])

      respond_to do |format|
        if @message.save
          format.html { redirect_to @message, notice: 'Message was successfully created.' }
          format.json { render json: @message, status: :created, location: @message }
        else
          format.html { render action: "new" }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /messages/1
    # PUT /messages/1.json
    def update
      @message = Message.find(params[:id])

      respond_to do |format|
        if @message.update_attributes(params[:message])
          format.html { redirect_to @message, notice: 'Message was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /messages/1
    # DELETE /messages/1.json
    def destroy
      @message = Message.find(params[:id])
      @message.destroy

      respond_to do |format|
        format.html { redirect_to messages_url }
        format.json { head :no_content }
      end
    end

  def resolve
    @message = Message.find(params[:id])
    @message.resolved = true
    @message.presentations.destroy_all
    @message.save
    head :no_content
  end

  def clear_resolved
    Message.where(resolved:true).destroy_all
    redirect_to root_url
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :traits_hash %><br />
    <%= f.text_area :traits_hash %>
  </div>
  <div class="field">
    <%= f.label :message_source_id %><br />
    <%= f.number_field :message_source_id %>
  </div>
  <div class="field">
    <%= f.label :message_source_type %><br />
    <%= f.text_field :message_source_type %>
  </div>
  <div class="field">
    <%= f.label :read %><br />
    <%= f.check_box :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_item.html.erb
<div class="message">
  <%= link_to 'dismiss', Presentation.where(message_id:message.id,inbox_id:@inbox.id).first, method: :delete %>
  <%= link_to 'resolve', resolve_message_path(id:message.id,return_url:request.fullpath) %>
  <b><%= message.source %></b>
  <%= message.message_subject %>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Message source</th>
    <th>Message source type</th>
    <th>Read</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.message_source_id %></td>
    <td><%= message.message_source_type %></td>
    <td><%= message.read %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<div id="message_basics">
	<!-- TODO programmatic display of message traits based on intelligently-defaulting template attached to presentation, rather than markup for each static trait as done below: -->
	<h3 class="centering"><%= @message.value('subject') %></h3>
	<p class="centering">from: <%= @message.value('sender') %></p>
	<% if @message.message_source %>
		<p class="centering">source: <%= @message.message_source.name %> (<%= @message.message_source.common_name %>)</p>
	<% end %>

      <% @message.traits.each do |trait| %>
        <p><b><%= trait.name %></b>: <%= trait.value %></p>
      <% end %>
</div>