config/routes.rb
Hermes::Application.routes.draw do
  
  match "/clear_resolved" => 'messages#clear_resolved'

  # message sources
    get "message_source/directory", as: 'message_source_directory'
    get "message_source/mine", as: 'my_message_sources'
    # post "message_sources/:message_id/check"

  resources :presentations
  match "/presentations_index_for_rule" => "presentations#index_for_rule"

  resources :rules
  match "/rules_index_for_inbox" => "rules#index_for_inbox"

  resources :traits


  resources :messages
  match '/resolve_message' => 'messages#resolve'

  resources :rss_feeds


  resources :inboxes
  match '/inbox_resolve_all_messages' => 'inboxes#resolve_all_messages'
  match '/inbox_check_for_messages' => 'inboxes#check_for_messages'
  match '/pull' => 'inboxes#pull'

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout
    
  resources :users

  root :to => 'home#index'

end

app/models/trait.rb
class Trait < ActiveRecord::Base
  attr_accessible :name, :traited_id, :traited_type, :value, :mode

  belongs_to :message, polymorphic: true
  belongs_to :rule, polymorphic: true
  belongs_to :rss_feed, polymorphic: true
  belongs_to :authorization, polymorphic: true

  def modes
  	{1=>'exact match',2=>"contains (case-agnostic)",3=>"contains (case-sensitive)"}
  end

  def pass?(value)
  	case self.mode
  	when 1
  		if value == self.value
  			return true
  		end
  	#TODO complete other modes here
  	else
  		return false
  	end
  	return false
  end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  # GET /traits
  # GET /traits.json
  def index
    @traits = Trait.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @traits }
    end
  end

  # GET /traits/1
  # GET /traits/1.json
  def show
    @trait = Trait.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trait }
    end
  end

  # GET /traits/new
  # GET /traits/new.json
  def new
    @trait = Trait.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trait }
    end
  end

  # GET /traits/1/edit
  def edit
    @trait = Trait.find(params[:id])
  end

  # POST /traits
  # POST /traits.json
  def create
    @trait = Trait.new(params[:trait])

    respond_to do |format|
      if @trait.save
        format.html { redirect_to @trait, notice: 'Trait was successfully created.' }
        format.json { render json: @trait, status: :created, location: @trait }
      else
        format.html { render action: "new" }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /traits/1
  # PUT /traits/1.json
  def update
    @trait = Trait.find(params[:id])

    respond_to do |format|
      if @trait.update_attributes(params[:trait])
        format.html { redirect_to @trait, notice: 'Trait was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traits/1
  # DELETE /traits/1.json
  def destroy
    @trait = Trait.find(params[:id])
    @trait.destroy

    respond_to do |format|
      format.html { redirect_to traits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/traits_helper.rb
module TraitsHelper
end

app/views/traits/_form.html.erb
<%= form_for(@trait) do |f| %>
  <% if @trait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trait.errors.count, "error") %> prohibited this trait from being saved:</h2>

      <ul>
      <% @trait.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :traited_id %><br />
    <%= f.number_field :traited_id %>
  </div>
  <div class="field">
    <%= f.label :traited_type %><br />
    <%= f.text_field :traited_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traits/edit.html.erb
<h1>Editing trait</h1>

<%= render 'form' %>

<%= link_to 'Show', @trait %> |
<%= link_to 'Back', traits_path %>

app/views/traits/index.html.erb
<h1>Listing traits</h1>

<table>
  <tr>
    <th>Traited</th>
    <th>Traited type</th>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @traits.each do |trait| %>
  <tr>
    <td><%= trait.traited_id %></td>
    <td><%= trait.traited_type %></td>
    <td><%= trait.name %></td>
    <td><%= trait.value %></td>
    <td><%= link_to 'Show', trait %></td>
    <td><%= link_to 'Edit', edit_trait_path(trait) %></td>
    <td><%= link_to 'Destroy', trait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trait', new_trait_path %>

app/views/traits/new.html.erb
<h1>New trait</h1>

<%= render 'form' %>

<%= link_to 'Back', traits_path %>

app/views/traits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Traited:</b>
  <%= @trait.traited_id %>
</p>

<p>
  <b>Traited type:</b>
  <%= @trait.traited_type %>
</p>

<p>
  <b>Name:</b>
  <%= @trait.name %>
</p>

<p>
  <b>Value:</b>
  <%= @trait.value %>
</p>


<%= link_to 'Edit', edit_trait_path(@trait) %> |
<%= link_to 'Back', traits_path %>