config/routes.rb
Hermes::Application.routes.draw do
  
  match "/clear_resolved" => 'messages#clear_resolved'

  # message sources
    get "message_source/directory", as: 'message_source_directory'
    get "message_source/mine", as: 'my_message_sources'
    # post "message_sources/:message_id/check"

  resources :presentations
  match "/presentations_index_for_rule" => "presentations#index_for_rule"

  resources :rules
  match "/rules_index_for_inbox" => "rules#index_for_inbox"

  resources :traits


  resources :messages
  match '/resolve_message' => 'messages#resolve'

  resources :rss_feeds


  resources :inboxes
  match '/inbox_resolve_all_messages' => 'inboxes#resolve_all_messages'
  match '/inbox_check_for_messages' => 'inboxes#check_for_messages'
  match '/pull' => 'inboxes#pull'

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout
    
  resources :users

  root :to => 'home#index'

end

app/models/rss_feed.rb
require 'message_source'
class RssFeed < ActiveRecord::Base
  include MessageSource

  attr_accessible :name, :url, :user_id

  belongs_to :user
  has_many :messages, as: :message_source
  has_many :traits, as: :traited

  after_create :default_present_to_news_inbox_template, :default_traits_creation

  validates :user, presence: true

  def default_present_to_news_inbox_template
    news = Inbox.where(template:'news',user_id:self.user.id).first_or_create
    news.name ||= "News"
    news.save
    rule = Rule.create(name:'Send all messages from source: '+self.name+' (RSS Feed) to inbox: '+news.name,user_id:self.user_id,passing_traits_needed_to_pass:0,passing_children_needed_to_pass:0)
    trait = rule.traits.create(name:'message_source_id',value:self.id.to_s)
    trait = rule.traits.create(name:'message_source_type',value:'rss_feed')
    presentation = rule.presentations.create(inbox_id:news.id)
  end

  def default_traits_creation
    # keeping all the traits is too expensive... specific traits to be generated for each message are authorized here by trait objects attached to the rss_feed.
    trait = self.traits.create(name:"title")
    trait = self.traits.create(name:"subject")
    trait = self.traits.create(name:"sender")
    trait = self.traits.create(name:"url")
    # very bad. these are included just for silly bad tests
      trait = self.traits.create(name:"color")
      trait = self.traits.create(name:"age")

  end

  def new_messages
    new_messages = []
    Feedzirra::Feed.fetch_and_parse(self.url).entries.each do |entry|
      #TODO better unique identifier, this one sucks
      if entry.published && self.messages.where(message_source_id:self.id,unique_identifier:entry.published).count == 0
        message = self.messages.create(unique_identifier:entry.published,message_source_id:self.id)

        title = entry.title || "no title"
        message.traits.create(name:'title',value:title)

        entry.instance_variables.each do |var| 
          if self.traits.where(name:var.to_s.delete("@")).count > 0
            message.traits.create(name:var.to_s.delete("@"),value:entry.instance_variable_get(var).to_s)
          end
        end

        message.traits.create(name:'message_source_type',value:'rss_feed')
        message.traits.create(name:'message_source_id',value:self.id)

        new_messages << message

        message.distribute!
      end
    end
    return new_messages
  end

  def common_name
    "RSS Feed"
  end
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  # GET /rss_feeds
  # GET /rss_feeds.json
  def index
    @rss_feeds = RssFeed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rss_feeds }
    end
  end

  # GET /rss_feeds/1
  # GET /rss_feeds/1.json
  def show
    @rss_feed = RssFeed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rss_feed }
    end
  end

  # GET /rss_feeds/new
  # GET /rss_feeds/new.json
  def new
    @rss_feed = RssFeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rss_feed }
    end
  end

  # GET /rss_feeds/1/edit
  def edit
    @rss_feed = RssFeed.find(params[:id])
  end

  # POST /rss_feeds
  # POST /rss_feeds.json
  def create
    @rss_feed = RssFeed.new(params[:rss_feed])
    @rss_feed.user = current_user
    
    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully created.' }
        format.json { render json: @rss_feed, status: :created, location: @rss_feed }
      else
        format.html { render action: "new" }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rss_feeds/1
  # PUT /rss_feeds/1.json
  def update
    @rss_feed = RssFeed.find(params[:id])

    respond_to do |format|
      if @rss_feed.update_attributes(params[:rss_feed])
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.json
  def destroy
    @rss_feed = RssFeed.find(params[:id])
    @rss_feed.destroy

    respond_to do |format|
      format.html { redirect_to rss_feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
end

app/views/rss_feeds/_form.html.erb
<%= form_for(@rss_feed) do |f| %>
  <% if @rss_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed.errors.count, "error") %> prohibited this rss_feed from being saved:</h2>

      <ul>
      <% @rss_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rss_feeds/edit.html.erb
<h1>Editing rss_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @rss_feed %> |
<%= link_to 'Back', rss_feeds_path %>

app/views/rss_feeds/index.html.erb
<h1>Listing rss_feeds</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rss_feeds.each do |rss_feed| %>
  <tr>
    <td><%= rss_feed.user_id %></td>
    <td><%= rss_feed.name %></td>
    <td><%= rss_feed.url %></td>
    <td><%= link_to 'Show', rss_feed %></td>
    <td><%= link_to 'Edit', edit_rss_feed_path(rss_feed) %></td>
    <td><%= link_to 'Destroy', rss_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rss feed', new_rss_feed_path %>

app/views/rss_feeds/new.html.erb
<h1>New RSS feed</h1>

<%= render 'form' %>

<%= link_to 'Back', rss_feeds_path %>

app/views/rss_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rss_feed.name %>
</p>

<p>
  <b>Url:</b>
  <%= @rss_feed.url %>
</p>


<%= link_to 'Edit', edit_rss_feed_path(@rss_feed) %> |
<%= link_to 'Back', rss_feeds_path %>