config/routes.rb
Hermes::Application.routes.draw do
  
  match "/clear_resolved" => 'messages#clear_resolved'

  # message sources
    get "message_source/directory", as: 'message_source_directory'
    get "message_source/mine", as: 'my_message_sources'
    # post "message_sources/:message_id/check"

  resources :presentations
  match "/presentations_index_for_rule" => "presentations#index_for_rule"

  resources :rules
  match "/rules_index_for_inbox" => "rules#index_for_inbox"

  resources :traits


  resources :messages
  match '/resolve_message' => 'messages#resolve'

  resources :rss_feeds


  resources :inboxes
  match '/inbox_resolve_all_messages' => 'inboxes#resolve_all_messages'
  match '/inbox_check_for_messages' => 'inboxes#check_for_messages'
  match '/pull' => 'inboxes#pull'

  #omniauth
    get   '/login', :to => 'sessions#new', :as => :login
    match '/auth/:provider/callback', :to => 'sessions#create'
    match '/auth/failure', :to => 'sessions#failure'
    get '/logout', :to => 'sessions#destroy', :as => :logout
    
  resources :users

  root :to => 'home#index'

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :name, :user_id, :passing_children_needed_to_pass, :parent_rule_id, :passing_traits_needed_to_pass

  belongs_to :user
  has_many :presentations
  has_many :traits, as: :traited

  def child_rules_pass?(message)
    if self.passing_children_needed_to_pass.nil?
      return true
    else
      # This is a meta-rule controlling children rules. Check child rules to make sure enough are satisfied to pass self.
      # TODO make more efficient. Should exit when needed_to_pass < satisfied
      satisfied = 0
      all_passed = true
      at_least_one_fail = false
      # TODO enable rules to have multiple parents, so child rules can be reused by different parents
      Rule.where(parent_rule_id:self.id).each do |child_rule|
        if child_rule.pass?(message)
          satisfied += 1
        else
          all_passed = false
          at_least_one_fail = true
        end
      end
      
      #pass if enough are met. If needed_to_pass is 0, pass if all passed
      if ((satisfied >= self.passing_children_needed_to_pass ) && (self.passing_children_needed_to_pass > 0)) || (self.passing_children_needed_to_pass == 0 && all_passed == true)
        return true
      elsif at_least_one_fail == true
        return false
      else
        return nil
      end
    end
  end

  def traits_pass?(message)
    if needed_to_pass = self.passing_traits_needed_to_pass
      # This is a meta-rule controlling children rules. Check child rules to make sure enough are satisfied to pass self.
      # TODO make more efficient. Should exit when needed_to_pass < satisfied
      satisfied = 0
      all_passed = true
      at_least_one_fail = false
      # TODO enable rules to have multiple parents, so child rules can be reused by different parents
      self.traits.each do |rule_trait|
        pass = false
        Trait.where(traited_id:message.id,traited_type:'Message',name:rule_trait.name).each do |matching_message_trait|
          if rule_trait.pass?(matching_message_trait.value)
            pass = true
          end
        end

        if pass
          satisfied += 1
        else
          all_passed = false
          at_least_one_fail = true
        end
      end
      
      #pass if enough are met. If needed_to_pass is 0, pass if all passed
      if (satisfied > needed_to_pass && needed_to_pass > 0) || (needed_to_pass == 0 && all_passed)
        true
      elsif at_least_one_fail == true
        false
      else
        nil
      end
    else
      true
    end
  end

  def pass?(message)
    if self.child_rules_pass?(message) && self.traits_pass?(message)
      return true
    else
      return false
    end
  end

	def process(message)
		if self.pass?(message)
			self.apply_presentations_to(message)
		end
	end

	def apply_presentations_to(message)
		self.presentations.each do |presentation|
			Presentation.create(inbox_id:presentation.inbox_id,message_id:message.id)
		end
	end

	def any_trait_matches(message)
		#TODO could be much more efficient
		pass = false

		self.traits.each do |rule_trait|
			message.traits.each do |message_trait|
				if rule_trait.name == message_trait.name && rule_trait.value == message_trait.value
					pass = true
				end
		end

		return pass
	end

	def super_string
		case self.super_mode
			when nil
				'not a super_rule'
			when 0
				'all meta_rule'
			when 2
				'any two rule'
			when 3
				'any three rule'
			else
				'any n rule'
			end
		end
	end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  # GET /rules
  # GET /rules.json

  # scaffolding methods
    def index
      @rules = Rule.all
      @title = "Hermes-wide rules"

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @rules }
      end
    end

    # GET /rules/1
    # GET /rules/1.json
    def show
      @rule = Rule.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @rule }
      end
    end

    # GET /rules/new
    # GET /rules/new.json
    def new
      @rule = Rule.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @rule }
      end
    end

    # GET /rules/1/edit
    def edit
      @rule = Rule.find(params[:id])
    end

    # POST /rules
    # POST /rules.json
    def create
      @rule = Rule.new(params[:rule])
      @rule.user = current_user

      respond_to do |format|
        if @rule.save
          format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
          format.json { render json: @rule, status: :created, location: @rule }
        else
          format.html { render action: "new" }
          format.json { render json: @rule.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /rules/1
    # PUT /rules/1.json
    def update
      @rule = Rule.find(params[:id])

      respond_to do |format|
        if @rule.update_attributes(params[:rule])
          format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @rule.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /rules/1
    # DELETE /rules/1.json
    def destroy
      @rule = Rule.find(params[:id])
      @rule.destroy

      respond_to do |format|
        format.html { redirect_to rules_url }
        format.json { head :no_content }
      end
    end

  def index_for_inbox
    @inbox = Inbox.find(params[:id])
    @rules = []
    #TODO optimize
    Presentation.where('rule_id IS NOT NULL AND inbox_id = ?',@inbox.id).each do |p|
      @rules << p.rule
    end
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1><%= @title %></h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.name %></td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/index_for_inbox.html.erb
<h1>rules sending messages to <%= @inbox.name %>:</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.name %></td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/rules_index_for_inbox.html.erb
<h1>rules sending messages to <%= @inbox.name %>:</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.name %></td>
    <td>"<%= rule.logic %>"</td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rule.name %>
</p>

<p><%= link_to 'presentations for this rule:'+@rule.presentations.count.to_s, presentations_index_for_rule_path(id:@rule) %></p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>